name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore MapWhenAlone.csproj

      - name: Build
        run: dotnet build MapWhenAlone.csproj -c Release

      - name: Package
        run: |
          VERSION=${GITHUB_REF_NAME}
          mkdir -p release/addons/counterstrikesharp/plugins/MapWhenAlone
          DLL=$(find bin/Release -name "MapWhenAlone.dll" | head -n 1)
          if [ -z "$DLL" ]; then
            echo "Could not find MapWhenAlone.dll"
            exit 1
          fi
          cp "$DLL" release/addons/counterstrikesharp/plugins/MapWhenAlone/
          cd release
          zip -r ../MapWhenAlone-${VERSION}.zip addons

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: MapWhenAlone-${{ github.ref_name }}.zip
